apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: husky-sawfish-go 
  janus-idp.io/tekton: husky-sawfish-go
  backstage.io/kubernetes-id: husky-sawfish-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: husky-sawfish-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  