apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: husky-sawfish-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: husky-sawfish-go 
  name: husky-sawfish-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: husky-sawfish-go 
