apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: husky-sawfish-go-gitops
  description: This is GitOps manifest for husky-sawfish-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: husky-sawfish-go
    janus-idp.io/tekton: husky-sawfish-go 
    backstage.io/kubernetes-id: husky-sawfish-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:husky-sawfish-go
